### ISSUE TITLE
ERROR: The type initializer for 'Autodesk.Connectivity.WebServicesTools.WebServiceManager' threw an exception.

### ISSUE THREAD

**Issue by AirWreckaStuff** [Autodesk/vault-admin-tools#1]
I just can't get past this error.  Running the 2017 version.  Also have the same issue in 2019. What am I doing wrong?
Thanks!

ERROR: The type initializer for 'Autodesk.Connectivity.WebServicesTools.WebServiceManager' threw an exception.
StackTrace:    at Autodesk.Connectivity.WebServicesTools.WebServiceManager.BracketIPv6HostName(String remoteHost)
   at Autodesk.DataManagement.Client.Framework.Vault.Currency.Connections.Connection..ctor(WebServiceManager mgr, String vault, Int64 userID, String server, AuthenticationFlags authFlags)
   at Autodesk.DataManagement.Client.Framework.Vault.Currency.Connections.Connection..ctor(WebServiceManager mgr, String userName, String password, String vault, Int64 userID, String server, AuthenticationFlags authFlags)
   at Autodesk.DataManagement.Client.Framework.Vault.Services.Implementation.VaultConnectionManagerService.GetExistingConnection_(String serverName, String vaultName, String userName, String password, AuthenticationFlags authFlags, Boolean updateConnectionRefCount)
   at Autodesk.DataManagement.Client.Framework.Vault.Services.Implementation.VaultConnectionManagerService.LogIn_(String serverName, String vaultName, String userName, String password, AuthenticationFlags authFlags, Guid alternateLicensekey, String alternateLicenseType, Func`3 progressCallback, VaultProductRequirements productConfiguration, EventHandler`1 connectionEstablishedHandler, EventHandler`1 connectionReusedHandler)
   at Autodesk.DataManagement.Client.Framework.Vault.Services.Implementation.VaultConnectionManagerService.LogIn(String serverName, String vaultName, String userName, String password, AuthenticationFlags authFlags, Func`3 progressCallback)
   at VaultUserAccounts.KnowledgeMaster..ctor(String server, String userName, String userPassword, AuthTyp authType) in C:\Users\Administrator\Documents\_Vault\vault-admin-tools-master\VaultUserAccounts\KnowledgeMaster.cs:line 21
   at VaultUserAccounts.Program.ExportUsers(VaultUserAccountsOptions options) in C:\Users\Administrator\Documents\_Vault\vault-admin-tools-master\VaultUserAccounts\Program.cs:line 126
   at VaultUserAccounts.Program.Run(VaultUserAccountsOptions options) in C:\Users\Administrator\Documents\_Vault\vault-admin-tools-master\VaultUserAccounts\Program.cs:line 78
   at VaultUserAccounts.Program.Main(String[] args) in C:\Users\Administrator\Documents\_Vault\vault-admin-tools-master\VaultUserAccounts\Program.cs:line 26

**Comment by katharineh** [comment]
Did you copy the following files from the Vault SDK into the directory containing your executable?

- Autodesk.Connectivity.WebServices.WCF.dll
- clmloader.dll

**Comment by AirWreckaStuff** [comment]
Of course, I missed that.  Thanks for your help, it's running!
